version: '3.7'
services:
  redbici:
    image: "node:14"
    build: .
    container_name: redbici
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ~/mongo:/data/db